function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 21-Apr-2020 22:10:25

% Create figure
figure;

% Create axes
axes1 = axes('YGrid','on','XGrid','on','ZColor',[0 0 0],...
    'YTick',[0 30 60 90 120 150],...
    'YColor',[0 0 0],...
    'XColor',[0 0 0],...
    'FontSize',13,...
    'Position',[0.13 0.111683501683502 0.775 0.812558922558923]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 101]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-5 155]);
box(axes1,'on');
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',1,'LineStyle','--');
set(plot1(1),'DisplayName','PSO','Marker','o','Color',[0 0 1]);
set(plot1(2),'DisplayName','FA','Marker','*',...
    'Color',[0.850980401039124 0.325490206480026 0.0980392172932625]);
set(plot1(3),'DisplayName','BAT','Marker','+','Color',[0 0 0]);

% Create xlabel
xlabel('Iterações','FontWeight','bold','FontSize',14);

% Create ylabel
ylabel('Usuários bloqueados','FontWeight','bold');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.779166666666667 0.769918591301066 0.110918560342185 0.117283947456431]);

